language: php

sudo: false

cache:
  directories:
    - bin
    - vendor
    - $HOME/.composer/cache

php:
  - 7.0

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer update --prefer-dist --no-interaction --no-progress

script:
  - vendor/bin/phpunit

notifications:
  email: false
