# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    enable_labels: false

services:
    app.webhook_resolver:
        class: Lpdigital\Github\Parser\WebhookResolver
        
    app.github.client:
        class: Github\Client
        arguments: []
        calls:
            - method: authenticate
              arguments:
                - http_token
                - %github_token%

    app.github.issues_api:
        class: Github\Api\Issue
        factory: ['@app.github.client', api]
        arguments: [issue]
        
    app.github.pullrequests_api:
        class: Github\Api\PullRequest
        factory: ['@app.github.client', api]
        arguments: [pull_request]
        
    app.github.labels_api:
        class: Github\Api\Issue\Labels
        factory: ['@app.github.issues_api', labels]

    app.github.cached_labels_api:
        class: AppBundle\Issues\CachedLabelsApi
        arguments: ['@app.github.labels_api', '%repository_username%', '%repository_name%']

    app.status_api:
        class: AppBundle\Issues\GitHubStatusApi
        arguments: ['@app.github.cached_labels_api', '%repository_username%', '%repository_name%']
        
    app.comment_api:
        class: AppBundle\Comments\GitHubCommentApi
        arguments: ['@app.github.issues_api', '%repository_username%', '%repository_name%']

    app.issue_listener:
        class: AppBundle\Issues\Listener
        arguments: ['@app.status_api']
    
    app.pullrequest_listener:
        class: AppBundle\PullRequests\Listener
        arguments: ['@app.comment_api', '@validator', '@twig']
    
    app.pullrequest_subscriber:
        class: AppBundle\EventSubscriber\PullRequestSubscriber
        calls: 
            - ['setContainer', ['@service_container']]
        tags:
            - { name: kernel.event_subscriber }
    
    app.issuecomment_subscriber:
        class: AppBundle\EventSubscriber\IssueCommentSubscriber
        calls: 
            - ['setContainer', ['@service_container']]
        tags:
            - { name: kernel.event_subscriber }
            
    app.issues_subscriber:
        class: AppBundle\EventSubscriber\IssuesSubscriber
        calls: 
            - ['setContainer', ['@service_container']]
        tags:
            - { name: kernel.event_subscriber }
